### PR TITLE
add getAuthToken method

### PR DESCRIPTION
**Pull request by noris666**
I need get auth token in my project and think add this function good idea, because i dont find any good solution without use AsyncStorage directly from react-native.

### CODE REVIEW

**Comment by Mokto** [comment]
Thanks, update coming now.

**Comment by eleventy** [comment]
Nice.  I've been using the token through AsyncStorage as a ( limited) way to verify that the app has been authenticated at least once when being offline.  This might make it cleaner.

**Comment by sabativi** [comment]
Hello @eleventy, could you elaborate a bit on how you did this ? I also want to display a Loggin View when user was loggedIn before but does not have internet access when opening the app again
Thanks

**Comment by eleventy** [comment]
@sabativi :
I check manually for the token in storage, because I also need other info from asyncStorage.  Only users with verified emails are allowed.  I use the token as a security-header for grahQL-calls

 In my  meteor wrapper component, I have a componentWillMount and componentWillReceiveProps:

```
componentWillMount(){
    checkActivated(this.props.dispatch)
  }
componentWillReceiveProps(nextProps){
    this.props.dispatch({ type:'METEOR_SET_DATA', payload:nextProps.data })
    if (nextProps.data.user.emails && nextProps.data.user.emails[0].verified){
      // user is logged in and verified
      setActivated(nextProps.data.user)
    }
    checkActivated(this.props.dispatch)
  }
```

The 2 functions:
```

const setActivated = async (user) => {
  // Mark the app as activated
  try {
    await AsyncStorage.setItem('@myApp:activated', 'true')
    await AsyncStorage.setItem('@myApp:username', user.username)
  } catch (error) {
    console.error("Error storing setActivated", error)
  }
}

const checkActivated = async dispatch => {
  const token = await AsyncStorage.getItem('reactnativemeteor_usertoken')
  const active = await AsyncStorage.getItem('@rmyApp:activated')
  const activated = active === 'true' ? true : false
  dispatch({ type:'METEOR_SET_ACTIVATED', payload:{ token, activated } })
}
```

When a user logs in, and is verified, the AsyncStorage is set( both the token and a activated flag).  When a user logges out, the storage is cleared.

And when there is no connection, the app is still marked activated.

dispatch is redux, but you could use any method

**Pull request merged**
