### PR TITLE
NetInfo change event changed to connectionChange event.

### LINKED ISSUE #272: RN 0.48.x: NetInfo change event deprecated for connectionChange event
In RN 0.48.x, The NetInfo change event listener has been deprecated and needs to be changed to connectionChange event listener.

### PR DESCRIPTION
**Pull request by ujwal-setlur**
Resolves #272

### CODE REVIEW

**Comment by mgscreativa** [comment]
Maybe you can check which RN version is currently installed so you can choose the NetInfo change event name, for backward compatibility. 

Maybe something like 
`const rnVersion = require('react-native/package.json').version`

**Comment by charpeni** [comment]
Thank you for your contribution @ujwal-setlur.

**Comment by mgscreativa** [comment]
WARNING! this change break backward compatibility with old RN versions...

**Comment by elie222** [comment]
We have an issue where now every time a user switches apps and back into our app, the login screen flashes up for a second and then they lose the place they were at in the app. I have a feeling it has to do with this update. Any ideas?

**Comment by ujwal-setlur** [comment]
This update should not have anything to do with what you are seeing. This was happening even before, at least for me. When app goes into background, I believe network connection to the server is lost. When the app comes back into focus, connectivity to meteor server is re-established. Depending on how your code is set up, when connection to meteor is restored, the login session is not quite set restored yet. During that time, login screen is shown. Then login session is restored, and the user is logged back in. Where the user ends up depends on your code. If you don't maintain any state in your app, your user will end up on the default screen after logging. At least that's how my app behaves. I have been meaning to add state management to the app, but haven't done it yet.

**Comment by elie222** [comment]
No it was definitely an update to the repo that broke it for us. It breaks in 1.0.6 for us. So I assume it's this:
https://github.com/inProgress-team/react-native-meteor/compare/1.0.6...master#diff-53dfeae4c43fde5283e3ca4afff51297R100

Works fine in 1.0.5 for us

**Pull request merged**
