### PR TITLE
#88

### PR DESCRIPTION
**Pull request by seanowenhayes**
Updated example to version 37 of react native and used containers for retrieving meteor data.

### CODE REVIEW

**Comment by noris666** [comment]
Thx for you PR. I check your changes tomorrow.
@Mokto @grsabreu also please check if have time.

**Comment by grsabreu** [comment]
thank you for your PR @seanowenhayes, I'm going to check tomorrow morning!

**Comment by grsabreu** [comment]
@noris666 I ran the new example and everything went fine! I did some minor modifications in the Example folder https://github.com/inProgress-team/react-native-meteor/tree/seanowenhayes-%2388 and committed to master.
If you think I did wrong please let me know!

**Comment by grsabreu** [comment]
Mainly the mods were:
- Update Meteor to 1.4.2.3
- Update the connection url from `http` to `ws:` protocol

**Comment by rgstephens** [comment]
I've just tested the update on android and the RN app aborts immediately on start.  Here's the output from logcat:

```
I/ActivityManager(  896): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.rnapp/.MainActivity bnds=[40,385][200,585] (has extras)} from uid 10031 on display 0
D/AndroidRuntime(25098): Shutting down VM
E/AndroidRuntime(25098): FATAL EXCEPTION: main
E/AndroidRuntime(25098): Process: com.rnapp, PID: 25098
E/AndroidRuntime(25098): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rnapp/com.rnapp.MainActivity}: java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication
E/AndroidRuntime(25098):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2339)
E/AndroidRuntime(25098):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
E/AndroidRuntime(25098):        at android.app.ActivityThread.access$800(ActivityThread.java:155)
E/AndroidRuntime(25098):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
E/AndroidRuntime(25098):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(25098):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(25098):        at android.app.ActivityThread.main(ActivityThread.java:5343)
E/AndroidRuntime(25098):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25098):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(25098):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
E/AndroidRuntime(25098):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
E/AndroidRuntime(25098): Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication
E/AndroidRuntime(25098):        at com.facebook.react.ReactActivityDelegate.getReactNativeHost(ReactActivityDelegate.java:72)
E/AndroidRuntime(25098):        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:80)
E/AndroidRuntime(25098):        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54)
E/AndroidRuntime(25098):        at android.app.Activity.performCreate(Activity.java:6010)
E/AndroidRuntime(25098):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
E/AndroidRuntime(25098):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
E/AndroidRuntime(25098):        ... 10 more
W/ActivityManager(  896):   Force finishing activity 1 com.rnapp/.MainActivity
```

**Pull request merged**
