### PR TITLE
fix not remove cache minimongo when reconnected

### PR DESCRIPTION
**Pull request by 2ducanhpham**

### CODE REVIEW

**Comment by goyan** [comment]
this seems required (batchUpdated undefined) with expo 18.0.0, ETA for merging?

**Comment by noris666** [comment]
@2ducanhpham please check your problems in package.json then we will try to test your code, better way if as yourself send for us mini report of test results. :-) good luck

**Comment by ujwal-setlur** [comment]
any update on this PR? Seems necessary

**Comment by ujwal-setlur** [comment]
This will not fix all the stale cache issues. Here is what I ran into:

- I have a subscription for "orders"
- I have an order in the orders collection.
- When I navigate to another screen on the react-native app, the subscription is stopped, but the order is still in the mini-mongo cache.
- I disconnect from Meteor and remove the order from server.
- I reconnect to Meteor. With this latest code, only active subscriptions get cleaned up for stale documents. However, my orders subscription is not active, so its stale document will not get cleaned out.
- When I navigate to the orders page, the subscription is activated, but the stale order is still in the cache and shows up.

**Pull request closed without merging**
