### PR TITLE
Don’t send message while the socket is closing

### PR DESCRIPTION
**Pull request by simonbelanger**

### CODE REVIEW

**Comment by noris666** [comment]
Can you say what means your code ? What problem solve this code ?
"Don't send message while the socket is closing" - it's too short.

Provide every time good descriptions for your pull requests.
Thanks.

**Comment by simonbelanger** [comment]
It's a fail-safe in case send() is called on the socket while it is closing (after the call to close(), but before the onclose callback)

**Comment by noris666** [comment]
@grsabreu @Mokto guys if you have time also please review this pull request and approve this. thx.

**Comment by grsabreu** [comment]
It seems ok to me!

**Comment by noris666** [comment]
Ok for me this code also good.

@simonbelanger thx 4 your pull request !

**Pull request merged**
