### PR TITLE
fixed mongo object ids transfer

### PR DESCRIPTION
**Pull request by constambeys**
Documents that contain mongo object ids are not transfered

### CODE REVIEW

**Comment by noris666** [comment]
@constambeys Hello ! I will check your PR in next days ! Thx for you PR !

**Comment by donedgardo** [comment]
Thank you @noris666 @constambeys

**Comment by noris666** [comment]
@donedgardo Sorry, I'm so busy lately. 
And cannot finally check this code right now :( 
Can you explain behavior of this new code ?

**Comment by donedgardo** [comment]
@noris666 it seems it adds recognition to different types of mongo ids: meteors and legacy mongo drivers. Also seems to be able to convert legacy ids to expected meteor mongo ids with a clone method. What is the prefered method of testing this, opening another repo with a meteor app(with a MongoId collection) and a React native app to test them out?

**Comment by noris666** [comment]
@constambeys @donedgardo 
Ok guys, in my opinion now this PR like tool for package. 
But for this PR we have 2 attached issues and for example with "-" problem does not solved.

@constambeys I ask to give a brief documentation of how this works.
I did not notice any changes with id work.
Next it will be clear whether to add or not.

**Comment by constambeys** [comment]
The code registers the Mongo.ObjectID to ejson using add type in mongo-id.js line 55.
The file is the same as meteor's mongo-id package displayed in the link at the beginning of the file.
In order to work I imported the EJSON package, meteor does it automatically using package utilities (Package.use).
I don't think this pull request breaks anything because it doesn't modify any code.

**Comment by noris666** [comment]
Merged ! Now we can use package from git :-)

**Pull request merged**
