### PR TITLE
Fix import for RN 0.46

### PR DESCRIPTION
**Pull request by charpeni**
The import path has changed with RN 0.46.

⚠️  Breaking change with RN < 0.46.

cc @Nauzer.

### CODE REVIEW

**Comment by theomathieubhvr** [comment]
Thanks. This should be tagged 1.1.0 cause it brokes previous RN versions

**Comment by Nauzer** [comment]
Great thanks will have a look later today or tomorrow to prepare the release.

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ujwal-setlur** [comment]
Quick question which is very likely ignorant, but...

Are these modules to be publicly consumed or are they meant for react-native's internal use? 

It seems react-native folks are doing quite a bit of code reorganizations, and this did not show up in the Release Notes as a breaking change.

**Comment by Nauzer** [comment]
@ujwal-setlur I get your point. However it was announced per https://github.com/facebook/react-native/commit/f3dbddcf2bdc0e4f49dd6f5220360b5ff383e16f#diff-834d77988fd4294e13e3e35533b3e248L161 to be removed with the note to use from direct 'deeper' packages based on necessity.

@charpeni - Shouldn't we start adding RN ^0.46 to the dependencies of this lib?

**Comment by ujwal-setlur** [comment]
Hi, any ETA of merging this?

**Comment by Nauzer** [comment]
I also confirm it works, but I would like to know if we maybe should start adding RN to the dependencies explicitly? It is now assuming it implicitly to be part of the project you're importing it to. However that can be an incompatible RN version.

My suggestion would be to make two new versions:

1.0.6 --> Add RN 0.45 to dependencies
1.1.0 --> Add RN 0.46 to dependencies

Any objections? @horensen @Mokto @charpeni

**Comment by charpeni** [comment]
@Nauzer Sounds good.

I'd say we should add it to peer dependencies instead of dependencies.

**Comment by noris666** [comment]
Yes guys, I checked this PR, it works.

**Comment by Nauzer** [comment]
@charpeni any chance you can add it to peer dependencies and update this PR?
I can then review and merge it. 

I could do it both but prefer to keep the traceable four-eye principle here :)

**Comment by charpeni** [comment]
@Nauzer Done. Please merge and release #253 before. 🚀

**Pull request merged**
