### PR TITLE
Update Example - Work in Progress

### PR DESCRIPTION
**Pull request by spencercarli**
This is still a work in progress but wanted to open it up to other eyes. I'm not sure how much time I can give to this over the next few weeks so if someone else wanted to take over I hope this can help.

Let me know if the example readme is covering all the necessary cases.

BTW the design is atrocious - not my area of expertise :)

### CODE REVIEW

**Comment by Mokto** [comment]
Hi @spencercarli !

Looking nice, I will be looking this more carefully when I get time. But I am pretty busy updating react-native-meteor already.

Thanks !

**Comment by Mokto** [comment]
This is what I would change :

## EDIT :
* `Meteor.subscribe` inside `getMeteorData` (remove startMeteorSubscriptions, now deprecated)

## ADD
* Meteor subscribe ready handle
* MeteorComplexListView
* Meteor.FSCollection('avatars').findOne()
* Meteor.user().profile.avatar.getFileRecord() (FS.File type must be parsed)

# ADD (low priority)
* Meteor.FSCollection('imagesFiles').insert)
* Meteor.FSCollection('imagesFiles').update
* Meteor.FSCollection('imagesFiles').remove
* FSCollectionImagesPreloader
* Eventually react-native-meteor-router-flux

**Comment by balibou** [comment]
@spencercarli @Mokto 
Guys thank you very much for all the work you're doing for this repo !

**Comment by spencercarli** [comment]
@Mokto took a few hours tonight to make some updates. I think the example is about as far as I can take it. Some of the API seems a little broken (list below). I don't know how to use FSCollection so I figured I would let you do that. 

- `MeteorComplexListView` makes app crash
-  `Meteor.status()` not react

**Comment by Mokto** [comment]
Ok merging and testing now !

Thanks.

**Pull request merged**
