### PR TITLE
Add support for collection transform and helpers

### PR DESCRIPTION
**Pull request by simonbelanger**
1. Add support for collection [transform](https://docs.meteor.com/api/collections.html#Mongo-Collection) function and [helpers](https://github.com/dburles/meteor-collection-helpers).
2. Refactor `Meteor.collection()` function to return an instance of Collection class instead of a literal.
3. Add an option (default to `false`) to make the return of `myColl.find()` looks like a cursor (added `fetch()` and `count()` methods.

Reasons for points 2 & 3 are :

- Facilitate eventual code sharing between react-native-meteor and Meteor core.
- Facilitate code sharing between a React Native application and a normal Meteor application.

### CODE REVIEW

**Comment by noris666** [comment]
Good PR ! I think we need ask @Mokto to add you in to contributors.

**Comment by Mokto** [comment]
Done ;)

**Comment by Mokto** [comment]
Thank you all for your good work.

**Comment by noris666** [comment]
@simonbelanger you are welcome !

**Comment by sscaff1** [comment]
Can a new version of React Native Meteor be pushed out to NPM so that we can have access to these methods without using the git repo?

**Comment by noris666** [comment]
@Mokto

**Comment by Mokto** [comment]
Done. v1.0.3

**Pull request merged**
