### PR TITLE
[WIP] Add resetPassword functionality

### PR DESCRIPTION
**Pull request by spencercarli**
Adds the ability to call `Accounts.resetPassword`

_Note:_ For some reason once you call the function you are not automatically signed in, as the doc specifies you should be. It's using the same logic that is being used when you sign in w/ an existing resume token so I'm not sure why that is working and this isn't. That should be fixed before a merge.

If you can point me to where this is happening from I can fix it

### CODE REVIEW

**Comment by Mokto** [comment]
Seems fine to me.

I need to try your code on my production app to see if everything is still working fine since we are in RC.

Soon soon ;)

**Comment by spencercarli** [comment]
Hey @Mokto anything I can do to help here?

**Comment by Mokto** [comment]
Sorry for not responding earlier.

Did you try your PR ? Code seems ok, and you added the functionality to auto-signin after.

So can I merge ?

Thanks !

**Comment by spencercarli** [comment]
Yes i'm using my branch currently in an app and haven't seen any issues beyond the one I outlined in the original description.

That issue also applies to `Accounts.createUser` though so in terms of the functionality added here, yes this is good to go.

**Comment by Mokto** [comment]
Ok then, thanks !

**Pull request merged**
